### ISSUE TITLE
Update Beatbump instance domain

### ISSUE THREAD

**Issue by giannilabella** [libredirect/instances#11]
The clearnet instance domain is no longer https://beatbump.ml, it is now https://beatbump.io/home
As said in [this](https://github.com/snuffyDev/Beatbump/issues/168) issue

**Comment by IkelAtomig** [comment]
We actually removed Beatbump service. It really is a good service and has a nice User experience too. But it doesn't follow YouTube URL schemes. So we couldn't redirect YT music to beatbump. It is just sitting ducks. hence we removed it.

**Comment by giannilabella** [comment]
Sorry, didn't realize that. Hadn't updated the extension. 
Opened the issue because saw the old domain [here](https://github.com/libredirect/instances/blob/b4cf091b282181a388e7006944531037152782b0/fixed/beatbump.json)

**Comment by ManeraKai** [comment]
I think we should remove it from there then.
