### ISSUE TITLE
lunar.icu instances not set as cloudflare

### ISSUE THREAD

**Issue by CaseOf** [libredirect/instances#12]
Hello,
I’ve noticed on the [hoster status page](https://status.max.srl/) that its instances are hosted through Cloudflare and that this is not defined as this in the extension.
Is it possible for you to fix this?
Sincerely,
Case_Of.

**Comment by ManeraKai** [comment]
Sorry for the late response. They have the Nameserver as Cloudflare, not the Content Delivery Network. This is fine. Our main concern is with the Content Delivery Network because, it sends unencrypted traffic to Cloudflare.
