### ISSUE TITLE
The Codeberg repository of this seems to be out of date

### ISSUE THREAD

**Issue by eownerdead** [libredirect/instances#14]
How about pushing this to the codeberg repository with GitHub Actions?
Regards

**Comment by ManeraKai** [comment]
I want to setup Codeberg's CI to be independent.

**Comment by IkelAtomig** [comment]
Is it possible, because I don't see any CI or alternatives to Github actions in Codeberg.

**Comment by ManeraKai** [comment]
There is something like this, but I couldn't use it back then: https://docs.codeberg.org/ci/

**Comment by IkelAtomig** [comment]
Well, we need to request via a form @ ci.codeberg.org

19 Aug 2024, by ***@***.***:

**Comment by ManeraKai** [comment]
Maybe it's better to make github actions update the codeberg repo.

**Comment by IkelAtomig** [comment]
You mean push aitomati6via webhooks instead of using independent CI ?

19 Aug 2024,  by ***@***.***:

**Comment by ManeraKai** [comment]
What is aitomati6via?

**Comment by IkelAtomig** [comment]
Automatically via, typographical mistake.

19 Aug 2024, by ***@***.***:

**Comment by ManeraKai** [comment]
GitHub Actions will simply make a git push to codeberg repo.
