### ISSUE TITLE
Several Teddit instances are going offline

### ISSUE THREAD

**Issue by 0xblur** [libredirect/instances#8]
Due to changes on the Reddit API, many Teddit instances have stopped their operations, such as and [tedd.it](https://tedd.it) and [teddit.totaldarkness.net](https://teddit.totaldarkness.net), which are two of the OGs. Probably more to come. I would suggest to delete these two from the instance list.

**Comment by ManeraKai** [comment]
Or remove teddit all together?

**Comment by 0xblur** [comment]
Not yet. Probably Reddit change its API policy and Teddit services can be kept alive. Otherwise, the logical step is to remove Teddit, and Libreddit.
